server:
  servlet:
    context-path: ${server.context-path}
  port: ${server.port}
  forward-headers-strategy: framework

spring:
  application:
    name: cooperacion-service
  profiles:
    active: dev
  config:
    #import: optional:configserver:http://192.168.1.120:9999/
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://192.168.100.48:7777/}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: false

  cloud:
    # Descubrimiento + Feign LoadBalancer
    discovery:
      enabled: true
    openfeign:
      loadbalancer:
        enabled: true
      client:
        config:
          aportacion-service:
            connectTimeout: ${feign.aportacion-service.connect-timeout:5000}
            readTimeout: ${feign.aportacion-service.read-timeout:8000}
            # url: ${feign.aportacion-service.url:}  # (opcional) bypass temporal de Eureka
    loadbalancer:
      cache:
        enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.cloud.client.discovery: INFO
    org.springframework.cloud.loadbalancer: INFO

eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.value}"
    prefer-ip-address: true
    ip-address: ${eureka.instance-ip}
    hostname: ${eureka.instance-host}
    non-secure-port: ${server.port}
    secure-port-enabled: false
  client:
    service-url:
      defaultZone: ${eureka.registry-server}
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: ${api-doc.config-url}
    url: ${api-doc.url}
    oauth2-redirect-url: https://supernovaworks.com.mx/gateway/cooperacion-service/swagger-ui/oauth2-redirect.html

api-doc:
  server-base-path: ${api-doc.server-base-path}

