server:
  servlet:
    context-path: /cooperacion-service
  port: 8087

spring:
  application:
    name: cooperacion-service 

  profiles:
    default: local 

  config:
    import: optional:configserver:http://192.168.1.120:9999/

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${db.username}
    hikari:
      maximum-pool-size: 5 
      connection-timeout: 20000 
    url: ${db.url} 
    password: ${db.password} 


  jpa:
    hibernate:
      ddl-auto: validate   # o update/create-drop según tu caso
    properties:
      hibernate.format_sql: false


  feign:
    client:
      config:
        aportacion-service:
          connectTimeout: 1500
          readTimeout: 2000


logging:
  level:

    org:
      hibernate:
        SQL: DEBUG # Muestra las consultas SQL generadas por Hibernate en la consola
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # Muestra también los valores que se "bindean" (asignan) a las consultas SQL

    org.springframework.cloud.stream: DEBUG
    org.apache.kafka: WARN

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}" # ID único para registrar esta instancia en Eureka (evita duplicados)
  client:
    service-url:   
      #defaultZone: http://192.168.100.48:8761/eureka/
      #defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      #defaultZone: "${eureka.registry-server}"
      defaultZone: http://192.168.1.120:8761/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui.html